### ISSUE TITLE
API Down - May 2017

### ISSUE THREAD

**Issue by JMTK** [KiaFathi/tambalAPI#5]
Hi! The API is down currently.

![image](https://cloud.githubusercontent.com/assets/877114/26329948/91acbe46-3f17-11e7-94dd-2f6712757f4c.png)

**Comment by JMTK** [comment]
Didn't realize the readme was updated

**Comment by KiaFathi** [comment]
@JMTK Should have it migrated by weekend. Will let you know when done, sorry about that.

**Comment by Bluscream** [comment]
https://tambalapi.herokuapp.com
